#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const catalogPath = path.resolve(__dirname, "../KeyboardManager/Localizable.xcstrings");
const catalog = JSON.parse(fs.readFileSync(catalogPath, "utf8"));

const translations = {
  "%@ erfassen": "Capture %@",
  "%@ wirklich löschen?": "Really delete %@?",
  "%@-Bestandsbericht wird erstellt und kontrolliert …": "%@ inventory report is being created and verified…",
  "%@-Bibliothek": "%@ library",
  "%lld": "%lld",
  "%lld Einträge": "%lld entries",
  "%lld Fotos": "%lld photos",
  "%lld Inventareinträge und %lld Fotos · SQLite-Integrität: %@": "%lld inventory entries and %lld photos · SQLite integrity: %@",
  "%lld bekannte Kandidaten wurden geprüft. ZIP, JSON oder ein anderer Datenordner können weiterhin manuell gewählt werden.": "%lld known candidates were checked. A ZIP, JSON, or another data folder can still be selected manually.",
  "%lld gesamt · %lld verfügbar": "%lld total · %lld available",
  "%lld von %lld": "%lld of %lld",
  "Abbrechen": "Cancel",
  "Aktuelle Filter anwenden": "Apply current filters",
  "Alle Pins": "All pins",
  "Allgemein": "General",
  "Als Hauptfoto": "Set as main photo",
  "Andere V1-Quelle auswählen …": "Select another V1 source…",
  "Artisan": "Artisan",
  "Backup fehlgeschlagen: %@": "Backup failed: %@",
  "Basisdaten": "Basic data",
  "Bearbeiten": "Edit",
  "Bekannte App-Support-Orte werden ausschließlich lesend geprüft …": "Known Application Support locations are being checked read-only…",
  "Bereitschaft": "Readiness",
  "Bericht fehlgeschlagen: %@": "Report failed: %@",
  "Bestand": "Inventory",
  "Bestand durchsuchen": "Search inventory",
  "Bestand exportieren …": "Export inventory…",
  "Bestandsbericht exportieren": "Export inventory report",
  "Bestandsübersicht": "Inventory overview",
  "Betroffen: %lld · %@": "Affected: %lld · %@",
  "Board": "Board",
  "Daten": "Data",
  "Datenhaltung": "Data storage",
  "Der Eintrag und seine verwalteten Fotos werden dauerhaft entfernt. Verknüpfungen werden konsistent gelöst.": "The entry and its managed photos will be permanently removed. Links will be resolved consistently.",
  "Der Eintrag, seine Fotos und seine Beziehungen werden konsistent entfernt.": "The entry, its photos, and its relationships will be removed consistently.",
  "Der Eintrag, seine verwalteten Fotos und seine Beziehungen werden konsistent entfernt.": "The entry, its managed photos, and its relationships will be removed consistently.",
  "Der aktuelle Entwurf wurde noch nicht gespeichert.": "The current draft has not been saved yet.",
  "Der vorherige V2-Bestand wurde als Backup erhalten.": "The previous V2 inventory was preserved as a backup.",
  "Der vorherige V2-Bestand wurde nicht verändert oder automatisch wiederhergestellt.": "The previous V2 inventory was not changed or was restored automatically.",
  "Details": "Details",
  "Details zu %@ öffnen": "Open details for %@",
  "Deutsch": "German",
  "Diese importierten Bildadressen werden nicht automatisch aufgerufen.": "These imported image addresses are not contacted automatically.",
  "Editoränderung": "Editor change",
  "Ein hinzugefügtes Foto kann als Hauptfoto markiert werden.": "An added photo can be set as the main photo.",
  "Eintrag nicht mehr verfügbar": "Entry no longer available",
  "Eintrag wirklich löschen?": "Really delete entry?",
  "English": "English",
  "Erfasse einen Eintrag mit Foto oder importiere deinen V1-Bestand.": "Capture an entry with a photo or import your V1 inventory.",
  "Erfasse einen neuen Eintrag oder importiere den V1-Bestand.": "Capture a new entry or import the V1 inventory.",
  "Erkannter Bestand": "Detected inventory",
  "Erneut suchen": "Search again",
  "Erstellt einen eigenständigen, kontrollierten Bericht aus dem aktuellen V2-Bestand.": "Creates a standalone, verified report from the current V2 inventory.",
  "Erstellt einen geprüften V2-Bestand; V1 bleibt unverändert": "Creates a verified V2 inventory; V1 remains unchanged",
  "Excel enthält eine Übersicht und je Bereich ein filterbares Tabellenblatt.": "Excel contains a summary and one filterable worksheet per section.",
  "Externe Importbilder": "External imported images",
  "Externe Importbilder lokal übernehmen?": "Import external images locally?",
  "Externe Importbilder – werden nicht automatisch geladen": "External imported images — not loaded automatically",
  "Externes Importbild": "External imported image",
  "Fenster mit ungespeicherten Änderungen schließen?": "Close window with unsaved changes?",
  "Filter zurücksetzen": "Reset filters",
  "Format": "Format",
  "Foto %@": "Photo %@",
  "Fotoimport fehlgeschlagen": "Photo import failed",
  "Fotos": "Photos",
  "Fotos hinzufügen …": "Add photos…",
  "Galerie durchsuchen": "Search gallery",
  "Gefundene V1-Quelle prüfen": "Check detected V1 source",
  "Gesamtbestand": "Complete inventory",
  "HTTPS-Quelladresse": "HTTPS source address",
  "Hauptfoto": "Main photo",
  "Hersteller": "Manufacturer",
  "Herunterladen und lokal übernehmen": "Download and import locally",
  "Import in V2 übernehmen …": "Import into V2…",
  "Importbilder herunterladen und lokal übernehmen …": "Download and import images locally…",
  "Importbilder werden geladen …": "Imported images are loading…",
  "Installationen": "Installations",
  "Installierte V1": "Installed V1",
  "Inventartyp": "Inventory type",
  "JPEG, PNG, GIF, WebP und HEIC; maximal 30 MiB. Große Bilder werden auf höchstens 1920 × 1080 Pixel skaliert.": "JPEG, PNG, GIF, WebP, and HEIC; maximum 30 MiB. Large images are scaled to at most 1920 × 1080 pixels.",
  "Kein Foto": "No photo",
  "Kein Hauptfoto": "No main photo",
  "Keine Treffer": "No matches",
  "Keine eindeutige V1-SQLite-Quelle gefunden": "No unambiguous V1 SQLite source found",
  "Keine Änderungen": "No changes",
  "Keyboard": "Keyboard",
  "Keyboard Manager": "Keyboard Manager",
  "Keyboard Manager Hauptfenster": "Keyboard Manager main window",
  "Keycap-Set": "Keycap set",
  "Kits, durch Komma getrennt": "Kits, separated by commas",
  "Komponenten": "Components",
  "LED-Diffusor": "LED diffuser",
  "Letzte Datenbankänderung: %@": "Last database change: %@",
  "Lokale Fotos": "Local photos",
  "Löschen": "Delete",
  "Materialien": "Materials",
  "Metadaten, Beziehungen, Prüfsummen und Bilddaten werden validiert …": "Metadata, relationships, checksums, and image data are being validated…",
  "Migration abgeschlossen": "Migration complete",
  "Migration fehlgeschlagen": "Migration failed",
  "Migrationshinweise": "Migration notes",
  "Migrationsmodus": "Migration mode",
  "Montage": "Mounting",
  "Nach Beenden erneut suchen": "Search again after quitting",
  "Name": "Name",
  "Name, Pflichtfeld": "Name, required",
  "Native V2": "Native V2",
  "Neu": "New",
  "Neuer Eintrag": "New entry",
  "Neues Board": "New board",
  "Nicht montiert": "Not mounted",
  "Nicht zugeordnet": "Unassigned",
  "Noch keine %@": "No %@ yet",
  "Noch keine Boards vorhanden.": "No boards yet.",
  "Noch keine Switch-Sets vorhanden.": "No switch sets yet.",
  "Noch keine lokalen Fotos.": "No local photos yet.",
  "Notizen": "Notes",
  "Nur lesen": "Read only",
  "Nächster Eintrag": "Next entry",
  "OK": "OK",
  "PCB: %@": "PCB: %@",
  "PDF enthält ein Deckblatt, wiederholte Tabellenköpfe und Seitenzahlen.": "PDF contains a cover page, repeated table headers, and page numbers.",
  "Passe Suche oder Filter an.": "Adjust the search or filters.",
  "Pins": "Pins",
  "Plate: %@": "Plate: %@",
  "Prüfergebnis": "Check result",
  "Prüflauf": "Dry run",
  "Prüfung fehlgeschlagen": "Check failed",
  "Quelle enthält blockierende Fehler": "Source contains blocking errors",
  "Quelle im Browser öffnen": "Open source in browser",
  "Quelle ist für den Import bereit": "Source is ready for import",
  "Quelle wird fixiert, Fotos werden kopiert und SQLite wird geprüft …": "Source is being fixed, photos are being copied, and SQLite is being checked…",
  "Restparität": "Remaining parity",
  "Rückgängig": "Undo",
  "Sammlung": "Collection",
  "Schließen": "Close",
  "Set-Inhalt": "Set contents",
  "Shop": "Shop",
  "Sortierung": "Sort",
  "Speichern": "Save",
  "Sprache": "Language",
  "Switch": "Switch",
  "Systemdarstellung verwenden": "Use system appearance",
  "Tags, durch Komma getrennt": "Tags, separated by commas",
  "Umfang": "Scope",
  "Ungespeicherte Änderungen": "Unsaved changes",
  "Ungespeicherte Änderungen verwerfen?": "Discard unsaved changes?",
  "Unterstützte Quellen": "Supported sources",
  "V1-Bestand in V2 übernehmen?": "Import V1 inventory into V2?",
  "V1-Migration": "V1 migration",
  "V1-Migration öffnen": "Open V1 migration",
  "V1-Quelle": "V1 source",
  "V1-Quelle auswählen …": "Select V1 source…",
  "V1-Quelle prüfen …": "Check V1 source…",
  "V1-kompatibles ZIP-Backup erstellen": "Create V1-compatible ZIP backup",
  "V2-Bestand erstellen": "Create V2 inventory",
  "V2-Bestand wird aufgebaut": "V2 inventory is being built",
  "V2-Bestand wurde erfolgreich aktiviert": "V2 inventory was activated successfully",
  "Validierungshinweise": "Validation notes",
  "Verbaut": "Installed",
  "Verfügbar": "Available",
  "Vorhandenen V2-Bestand sichern und ersetzen": "Back up and replace existing V2 inventory",
  "Vorhandenen Wert auswählen; freie Eingabe bleibt möglich.": "Select an existing value; free-form input remains available.",
  "Vorheriger Eintrag": "Previous entry",
  "Vorschaubilder einbetten": "Embed preview images",
  "Wege und Kräfte": "Travel and forces",
  "Weiter bearbeiten": "Keep editing",
  "Weiter …": "Continue…",
  "Werkseitig geschmiert": "Factory lubed",
  "Wird gespeichert …": "Saving…",
  "Wähle ein V1-ZIP (Schema 3–6), ein älteres JSON-Vollbackup oder den V1-Datenordner mit keyboard-manager.sqlite und photos/. Beende V1 vor einer direkten SQLite-Prüfung. Die Quelle bleibt unverändert.": "Select a V1 ZIP (schema 3–6), an older full JSON backup, or the V1 data folder containing keyboard-manager.sqlite and photos/. Quit V1 before a direct SQLite check. The source remains unchanged.",
  "ZIP-Backup": "ZIP backup",
  "ZIP-Backup wird erstellt und kontrolliert …": "ZIP backup is being created and verified…",
  "Zum lokalen Übernehmen bearbeiten": "Edit to import locally",
  "Zusatz": "Additional",
  "von %lld": "of %lld",
  "· %lld HEIC als JPEG kopiert": "· %lld HEIC copied as JPEG",
  "Änderungen verwerfen": "Discard changes",
  "Änderungen verwerfen und schließen": "Discard changes and close",
  "Öffnet die Großansicht": "Opens the large view",

  "%@ · %lld Stück": "%@ · %lld pieces",
  "Aktueller Inventartyp": "Current inventory type",
  "Betätigungskraft": "Operating force",
  "Die Sprachauswahl konnte nicht gespeichert werden: %@": "The language selection could not be saved: %@",
  "Fachfeld": "Category field",
  "Galerie": "Gallery",
  "Gesamter Bestand": "Complete inventory",
  "Keycap-Sets": "Keycap sets",
  "Menge absteigend": "Quantity descending",
  "SQLite · lokal": "SQLite · local",
  "Nur lesende V1-Quelle": "Read-only V1 source",
  "Stabilisatoren": "Stabilizers",
  "Typ": "Type",
  "Übersicht": "Overview",
  "Erfassen": "Capture",
  "Zuletzt geändert": "Last changed",
  "%@-Bestandsbericht speichern": "Save %@ inventory report",
  "%lld Einträge · %@": "%lld entries · %@",
  "%lld Einträge · Filter: %@": "%lld entries · Filters: %@",
  "Angewendet": "Applied",
  "Backup sichern": "Save backup",
  "Bereich": "Section",
  "Bericht sichern": "Save report",
  "Bestandsbericht": "Inventory report",
  "Bottom Housing": "Bottom housing",
  "Das Berichtsdokument konnte nicht erzeugt werden.": "The report document could not be created.",
  "Das Bildformat von „%@“ wird nicht unterstützt.": "The image format of “%@” is not supported.",
  "Das erzeugte Backup hat die Kontrollprüfung nicht bestanden: %@": "The generated backup failed verification: %@",
  "Das fertige ZIP überschreitet das Limit von 500 MiB.": "The completed ZIP exceeds the 500 MiB limit.",
  "Das Foto „%@“ konnte nicht für den PDF-Bericht gelesen werden.": "The photo “%@” could not be read for the PDF report.",
  "Das gewählte Backup-Ziel ist ungültig.": "The selected backup destination is invalid.",
  "Das gewählte Berichtsziel ist ungültig.": "The selected report destination is invalid.",
  "Das Hauptfoto gehört nicht zur Fotoliste dieses Eintrags.": "The main photo does not belong to this entry's photo list.",
  "Das HEIC-Foto „%@“ konnte nicht kompatibel als JPEG exportiert werden.": "The HEIC photo “%@” could not be exported compatibly as JPEG.",
  "Das externe Importbild von „%@“ konnte nicht geladen werden.": "The external imported image from “%@” could not be loaded.",
  "Dateiname:": "File name:",
  "Der Bericht enthält ungültige Daten: %@": "The report contains invalid data: %@",
  "Der Bericht überschreitet das Limit von 40.000 Zeilen.": "The report exceeds the limit of 40,000 rows.",
  "Der Bestand überschreitet die vom Backupformat erlaubte Anzahl von Einträgen.": "The inventory exceeds the number of entries allowed by the backup format.",
  "Der bereitgestellte V2-Bestand hat die Abschlussprüfung nicht bestanden: %@": "The prepared V2 inventory failed final verification: %@",
  "Der gespeicherte V2-Bestand ist nicht lesbar: %@": "The saved V2 inventory is unreadable: %@",
  "Der Import ist durch Fehler im Prüflauf blockiert.": "The import is blocked by errors in the dry run.",
  "Der interne Foto-Stagingplan ist ungültig.": "The internal photo staging plan is invalid.",
  "Der interne Fotodateiname „%@“ ist ungültig.": "The internal photo file name “%@” is invalid.",
  "Der Name ist ein Pflichtfeld.": "The name is required.",
  "Der vorhandene V2-Datenordner ist kein reguläres Verzeichnis.": "The existing V2 data folder is not a regular directory.",
  "Der V2-Bestand konnte nicht serialisiert werden: %@": "The V2 inventory could not be serialized: %@",
  "Der zu bearbeitende Eintrag wurde nicht gefunden.": "The entry to edit was not found.",
  "Die Bestandsdaten überschreiten das Manifest-Limit von 10 MiB.": "The inventory data exceeds the 10 MiB manifest limit.",
  "Die Fotodaten überschreiten das Backup-Limit von 500 MiB.": "The photo data exceeds the 500 MiB backup limit.",
  "Die interne ID „%@“ ist nicht mit dem V1-Backupformat kompatibel.": "The internal ID “%@” is not compatible with the V1 backup format.",
  "Die Kontrollprüfung des Berichts ist fehlgeschlagen: %@": "Report verification failed: %@",
  "Die SQLite-Integritätsprüfung ist fehlgeschlagen: %@": "SQLite integrity verification failed: %@",
  "Die URL „%@“ muss eine vollständige HTTPS-Adresse sein.": "The URL “%@” must be a complete HTTPS address.",
  "Die V1-Quelle hat sich seit dem Prüflauf verändert. Bitte erneut prüfen.": "The V1 source has changed since the dry run. Please check it again.",
  "Die V2-Datenbank konnte nicht geöffnet werden: %@": "The V2 database could not be opened: %@",
  "Die V2-Datenbankoperation ist fehlgeschlagen: %@": "The V2 database operation failed: %@",
  "Die verknüpfte Position „%@“ existiert nicht mehr.": "The linked item “%@” no longer exists.",
  "Die verwaltete Fotodatei „%@“ fehlt.": "The managed photo file “%@” is missing.",
  "Ein interner Fotodateiname war ungültig.": "An internal photo file name was invalid.",
  "Eine Berichtstabelle überschreitet das Limit von 32 Spalten.": "A report table exceeds the limit of 32 columns.",
  "Einträge": "Entries",
  "Erstellt": "Created",
  "Externe Importbilder müssen vollständige HTTPS-Adressen ohne Zugangsdaten verwenden.": "External imported images must use complete HTTPS addresses without credentials.",
  "Federlänge": "Spring length",
  "Federtyp": "Spring type",
  "Filter": "Filters",
  "Fotos konnten nicht sicher bereitgestellt werden: %@": "Photos could not be prepared safely: %@",
  "Foto": "Photo",
  "Geändert": "Changed",
  "Gesamtweg": "Total travel",
  "Ja": "Yes",
  "Keyboard Manager Bestand": "Keyboard Manager inventory",
  "Keyboard Manager V1 ist noch geöffnet. Bitte V1 vollständig beenden und die Suche erneut ausführen.": "Keyboard Manager V1 is still open. Quit V1 completely and search again.",
  "Keycaps": "Keycaps",
  "Keine aktiven Filter": "No active filters",
  "Keine Einträge in diesem Bereich.": "No entries in this section.",
  "Kits": "Kits",
  "Kraft: %@": "Force: %@",
  "Nein": "No",
  "Nicht angewendet": "Not applied",
  "Pins: %@": "Pins: %@",
  "Profil": "Profile",
  "Profil: %@": "Profile: %@",
  "Quelle": "Source",
  "Quell-URL": "Source URL",
  "Seite %lld": "Page %lld",
  "Simulierter Aktivierungsfehler.": "Simulated activation failure.",
  "Status: %@": "Status: %@",
  "Suche: %@": "Search: %@",
  "Tags": "Tags",
  "Top Housing": "Top housing",
  "Typ: %@": "Type: %@",
  "Übersicht des exportierten Bestands": "Summary of the exported inventory",
  "„%@“ hat keine gültige HTTPS-Bildantwort geliefert.": "“%@” did not return a valid HTTPS image response.",
  "„%@“ konnte nicht als Bild gelesen werden.": "“%@” could not be read as an image.",
  "„%@“ konnte nicht für die Mediathek aufbereitet werden.": "“%@” could not be prepared for the media library.",
  "„%@“ überschreitet das Backup-Limit von 30 MiB.": "“%@” exceeds the 30 MiB backup limit.",
  "„%@“ überschreitet das Limit von 30 MiB.": "“%@” exceeds the 30 MiB limit.",
  "Artisans": "Artisans",
  "Bilddaten konnten nicht dekodiert werden: %@": "Image data could not be decoded: %@",
  "Bitte den V1-Datenordner auswählen, der keyboard-manager.sqlite und photos/ enthält.": "Select the V1 data folder containing keyboard-manager.sqlite and photos/.",
  "Bitte ein V1-ZIP-Backup, ein Legacy-JSON-Backup oder den V1-Datenordner auswählen.": "Select a V1 ZIP backup, a legacy JSON backup, or the V1 data folder.",
  "%lld Quelle(n) bereit": "%lld source(s) ready",
  "0 von %lld": "0 of %lld",
  "Betätigung": "Operating force",
  "Bottom-out": "Bottom-out",
  "CRC-Prüfung fehlgeschlagen: %@": "CRC check failed: %@",
  "Das Backup enthält mehr Einträge als erlaubt.": "The backup contains more entries than allowed.",
  "Das Backup überschreitet das Limit von 500 MiB.": "The backup exceeds the 500 MiB limit.",
  "Das Legacy-JSON ist nicht lesbar oder kein vollständiges V1-Backup.": "The legacy JSON is unreadable or is not a complete V1 backup.",
  "Das Manifest ist kein Keyboard-Manager-ZIP-Backup.": "The manifest is not a Keyboard Manager ZIP backup.",
  "Das Manifest überschreitet das Limit von 10 MiB.": "The manifest exceeds the 10 MiB limit.",
  "Das V1-Manifest ist nicht lesbar oder unvollständig.": "The V1 manifest is unreadable or incomplete.",
  "Das ZIP enthält kein manifest.json.": "The ZIP does not contain manifest.json.",
  "Das ZIP-Archiv konnte nicht sicher geöffnet werden.": "The ZIP archive could not be opened safely.",
  "Der aktuelle V2-Bestand wird zuerst vollständig in Backups verschoben. Danach wird der geprüfte Staging-Bestand aktiviert. Die V1-Quelle wird nicht verändert.": "The current V2 inventory is first moved completely into backups. The verified staging inventory is then activated. The V1 source is not changed.",
  "Der gewählte V1-Datenordner oder eine benötigte Quelle ist kein regulärer, sicher lesbarer Pfad.": "The selected V1 data folder or a required source is not a regular, safely readable path.",
  "Die ausgewählte Quelle ist keine reguläre Backup-Datei.": "The selected source is not a regular backup file.",
  "Die entpackten Fotodaten überschreiten das Limit von 500 MiB.": "The extracted photo data exceeds the 500 MiB limit.",
  "Die kopierte V1-Datenbank hat die Integritätsprüfung nicht bestanden: %@": "The copied V1 database failed integrity verification: %@",
  "Die V1-App-Metadaten sind nicht lesbar.": "The V1 app metadata is unreadable.",
  "Die V1-Datenbank einschließlich WAL überschreitet das Limit von 100 MiB.": "The V1 database including its WAL exceeds the 100 MiB limit.",
  "Die V1-Datenbank konnte nicht ausschließlich lesend geöffnet werden: %@": "The V1 database could not be opened read-only: %@",
  "Die V1-Datenbank konnte nicht konsistent in V2-Staging kopiert werden: %@. Bitte V1 vollständig beenden und erneut versuchen.": "The V1 database could not be copied consistently into V2 staging: %@. Quit V1 completely and try again.",
  "Die V1-Datenbank besitzt nicht das erwartete Schema: %@": "The V1 database does not have the expected schema: %@",
  "Die V1-Datenbank referenziert Fotos, aber der Ordner photos/ fehlt.": "The V1 database references photos, but the photos/ folder is missing.",
  "Die V1-Fotodaten überschreiten das Limit von 500 MiB.": "The V1 photo data exceeds the 500 MiB limit.",
  "Die V1-Fotodatei %@ überschreitet das Limit von 30 MiB.": "The V1 photo file %@ exceeds the 30 MiB limit.",
  "Doppelte ID bei %@.": "Duplicate ID for %@.",
  "Doppelter ZIP-Eintrag: %@": "Duplicate ZIP entry: %@",
  "Ein Datensatz in %@ ist nicht lesbar oder seine ID stimmt nicht mit dem JSON-Inhalt überein.": "A record in %@ is unreadable or its ID does not match the JSON content.",
  "Eingebettete Bilddaten sind ungültig oder zu groß: %@": "Embedded image data is invalid or too large: %@",
  "Eine V1-Fotodatei fehlt oder besitzt einen unsicheren Dateinamen: %@": "A V1 photo file is missing or has an unsafe file name: %@",
  "Format: %@": "Format: %@",
  "Hersteller: %@": "Manufacturer: %@",
  "IndexedDB/localStorage-Export": "IndexedDB/localStorage export",
  "Installierte V1-Datenbank": "Installed V1 database",
  "Im gewählten Ordner fehlt keyboard-manager.sqlite.": "keyboard-manager.sqlite is missing from the selected folder.",
  "Im ZIP fehlt eine referenzierte Fotodatei: %@": "A referenced photo file is missing from the ZIP: %@",
  "JSON-Schema %lld ist kein unterstütztes Legacy-Backup.": "JSON schema %lld is not a supported legacy backup.",
  "Keycap-Sets": "Keycap sets",
  "Keyboards": "Keyboards",
  "Legacy-JSON-Backup": "Legacy JSON backup",
  "Migration blockiert": "Migration blocked",
  "Nicht unterstützter Fototyp: %@": "Unsupported photo type: %@",
  "Noch keine Quelle ausgewählt": "No source selected yet",
  "PCB": "PCB",
  "Plate": "Plate",
  "Pre-Travel": "Pre-travel",
  "Probe, Validierung, Vorschau und explizite Bestätigung gehen jedem späteren Commit voraus.": "Dry run, validation, preview, and explicit confirmation precede every later commit.",
  "Sonderpfad für sehr alte Installationen": "Special path for very old installations",
  "Stem": "Stem",
  "Switches": "Switches",
  "Ungültige oder fehlende ID bei %@.": "Invalid or missing ID for %@.",
  "Unsicherer oder unerwarteter ZIP-Eintrag: %@": "Unsafe or unexpected ZIP entry: %@",
  "V1-Quelle wird geprüft": "V1 source is being checked",
  "V1-Schema 3–6 mit Manifest und separaten Fotos": "V1 schema 3–6 with manifest and separate photos",
  "V1-ZIP-Backup (empfohlen)": "V1 ZIP backup (recommended)",
  "V2 fixiert die Quelle zunächst in einem eigenen Staging-Bereich, prüft Hash, Fotos und SQLite erneut und aktiviert den Bestand erst nach erfolgreicher Abschlussprüfung. V1 bleibt unverändert.": "V2 first fixes the source in a dedicated staging area, checks the hash, photos, and SQLite again, and activates the inventory only after successful final verification. V1 remains unchanged.",
  "ZIP-Backup-Schema %lld wird nicht unterstützt; erwartet wird Schema 3 bis 6.": "ZIP backup schema %lld is not supported; schema 3 through 6 is expected.",
  "ZIP-Eintrag überschreitet sein Größenlimit: %@": "ZIP entry exceeds its size limit: %@",
  "den hinterlegten Bildservern": "the stored image servers",
  "Älteres Vollbackup mit eingebetteten Fotos": "Older full backup with embedded photos",
  "%@ ohne Namen können nicht importiert werden.": "%@ without a name cannot be imported.",
  "Boards referenzieren nicht vorhandene Keycap-Sets.": "Boards reference missing keycap sets.",
  "Boards referenzieren nicht vorhandene Switch-Sets.": "Boards reference missing switch sets.",
  "Das PDF enthält keine lesbare Seite.": "The PDF does not contain a readable page.",
  "Das PDF-Deckblatt konnte nicht gelesen werden.": "The PDF cover page could not be read.",
  "Datenbankdatei fehlt.": "The database file is missing.",
  "Dekodierte Bildabmessungen weichen von V1-Metadaten ab.": "Decoded image dimensions differ from the V1 metadata.",
  "Der dekodierte Bildtyp weicht von V1 ab und wird anhand der Bilddaten normalisiert.": "The decoded image type differs from V1 and is normalized based on the image data.",
  "Der Gesamtbestand darf nicht negativ sein.": "The total inventory cannot be negative.",
  "Die direkte V1-Datenbank wurde ausschließlich lesend in einen konsistenten V2-Staging-Snapshot überführt.": "The direct V1 database was transferred read-only into a consistent V2 staging snapshot.",
  "Die erzeugte Datei ist leer.": "The generated file is empty.",
  "Die Excel-Datei ist kein lesbares ZIP-Paket.": "The Excel file is not a readable ZIP package.",
  "Die Tabellenzeilen passen nicht zu ihren Spalten.": "The table rows do not match their columns.",
  "Doppelte Switch-/Board-Installationen wurden zusammengeführt.": "Duplicate switch/board installations were merged.",
  "Ein älteres V1-ZIP-Schema wird kontrolliert auf das aktuelle V2-Modell normalisiert.": "An older V1 ZIP schema is safely normalized to the current V2 model.",
  "Eingebettete Legacy-Fotos werden vor dem Import in getrennte, geprüfte Dateien überführt.": "Embedded legacy photos are converted to separate, verified files before import.",
  "Es müssen ein bis vier Bereiche enthalten sein.": "One to four sections must be included.",
  "Explizite Switch-Installationen gewinnen bei widersprüchlichen Board-Mengen.": "Explicit switch installations take precedence when board quantities conflict.",
  "Fotos besitzen keinen gültigen Inventar-Eigentümer.": "Photos do not have a valid inventory owner.",
  "Für „%@“ wären %lld von %lld Switches verbaut.": "For “%@”, %lld of %lld switches would be installed.",
  "Gesamt": "Total",
  "Hauptfotos gehören nicht zur Fotoliste ihres Eintrags.": "Main photos do not belong to their item's photo list.",
  "Im Excel-Paket fehlen Pflichtdateien.": "Required files are missing from the Excel package.",
  "Installationsmengen dürfen nicht negativ sein.": "Installation quantities cannot be negative.",
  "Inventareinträge referenzieren nicht vorhandene Fotos.": "Inventory items reference missing photos.",
  "Komponenten referenzieren nicht vorhandene Boards.": "Components reference missing boards.",
  "Material": "Material",
  "Nicht alle Tabellenblätter wurden geschrieben.": "Not all worksheets were written.",
  "Nicht-HTTPS- oder ungültige externe URLs werden nicht übernommen.": "Non-HTTPS or invalid external URLs are not imported.",
  "PDF-Signatur fehlt.": "The PDF signature is missing.",
  "Snapshot enthält keine Daten.": "The snapshot does not contain any data.",
  "SQLite-Fehler %lld": "SQLite error %lld",
  "SQLite-Rückleseprobe weicht ab.": "The SQLite read-back check differs.",
  "Status": "Status",
  "Switch-Installationen werden als kanonische Beziehung übernommen, obwohl die Board-Rückseite fehlt.": "Switch installations are imported as the canonical relationship even though the board backlink is missing.",
  "V1-Importhinweise werden zur späteren Prüfung erhalten.": "V1 import warnings are preserved for later review.",
  "Verbaut (%lld) darf den Gesamtbestand (%lld) nicht überschreiten.": "Installed (%lld) cannot exceed total inventory (%lld).",
  "ZIP-Backup speichern": "Save ZIP backup"
};

for (const [key, value] of Object.entries(translations)) {
  const entry = catalog.strings[key] ?? {};
  entry.localizations = entry.localizations ?? {};
  entry.localizations.en = {
    stringUnit: {
      state: "translated",
      value
    }
  };
  catalog.strings[key] = entry;
}

const missing = Object.keys(catalog.strings).filter((key) => !translations[key]);
if (missing.length > 0) {
  throw new Error(`Missing English translations:\n${missing.join("\n")}`);
}

function swiftFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return swiftFiles(entryPath);
    return entry.isFile() && entry.name.endsWith(".swift") ? [entryPath] : [];
  });
}

const runtimeKeys = new Set();
const runtimeKeyPattern = /L10n\.text\(\s*"((?:\\.|[^"\\])*)"/g;
for (const filePath of swiftFiles(path.resolve(__dirname, "../KeyboardManager"))) {
  const source = fs.readFileSync(filePath, "utf8");
  for (const match of source.matchAll(runtimeKeyPattern)) {
    runtimeKeys.add(JSON.parse(`"${match[1]}"`));
  }
}
const missingRuntimeKeys = [...runtimeKeys].filter((key) => !translations[key]).sort();
if (missingRuntimeKeys.length > 0) {
  throw new Error(
    `Missing English translations for L10n.text keys:\n${missingRuntimeKeys.join("\n")}`
  );
}

const ordered = Object.fromEntries(
  Object.entries(catalog.strings).sort(([left], [right]) => left.localeCompare(right, "de"))
);
catalog.strings = ordered;
fs.writeFileSync(catalogPath, `${JSON.stringify(catalog, null, 2)}\n`);
console.log(`Updated ${Object.keys(catalog.strings).length} localized strings.`);
